sudo: required
language: generic

services:
  - docker

before install:
  - docker build -t colleenberbon/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true colleenberbon/docker-react-aws npm run test 