sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t colleenberbon/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true colleenberbon/docker-react-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-aws"
  env: "DockerReactAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-265913181504"
  bucket_path: "docker-react-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY